name: General Report
description: Provide general feedback or inquiries
title: "[General]: "
labels: ["general"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide general feedback or inquiries! Please fill out the form below to help us understand your feedback.

  - type: textarea
    id: feedback
    attributes:
      label: Feedback or Inquiry
      description: Please provide your feedback or inquiry
      placeholder: Describe your feedback or inquiry here
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Links, screenshots, code snippets, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting the general report
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have tested with the latest version of Peek-a-Repo
          required: true

